### ISSUE TITLE
Decouple from settings.LANGUAGE_CODE

### ISSUE THREAD

**Issue by jacobwegner** [zostera/django-modeltrans#116]
I have a use case where I want to use [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) language codes with `modeltrans`.

Django's `LocaleMiddleware` will fail if `settings.LANGUAGE_CODE` does not have translation files.

For example the following configuration:

```python
# settings.py
MIDDLEWARE = [
    # ...
    "django.middleware.locale.LocaleMiddleware",
    # ...
]

LANGUAGE_CODE = "eng"
MODELTRANS_AVAILABLE_LANGUAGES = ["nld", "deu", "fra"]
```

Raises the following error:
```
# https://github.com/django/django/blob/34f329ecac79d2d40df5ed83233ea8e42a5f530f/django/utils/translation/trans_real.py#L173
OSError: No translation files found for default language eng.
```

Adding a new setting `MODELTRANS_DEFAULT_LANGUAGE` would allow decoupling from `LANGUAGE_CODE`, e.g.

```
LANGUAGE_CODE = "en-US"   # the default from https://github.com/django/django/blob/34f329ecac79d2d40df5ed83233ea8e42a5f530f/django/conf/global_settings.py#L48
MODELTRANS_DEFAULT_LANGUAGE = "eng"
MODELTRANS_AVAILABLE_LANGUAGES = ["nld", "deu", "fra"]
```

**Comment by julianwachholz** [comment]
Hi Jacob, have you tried it with the fallback setting like this? Does it work in the same way or does it behave differently?

```python
MODELTRANS_FALLBACK = {
   'default': ('eng', ),
}
```

**Comment by jacobwegner** [comment]
@julianwachholz: Thank you for the suggestion, but unfortunately, I don't think that covers my use case.

I want to be able to reference a field `title` as `title_eng`, title_fra`, etc.

If I add `eng` to `MODELTRANS_FALLBACK`, I must also add it to `MODELTRANS_AVAILABLE_LANGUAGES` (refs https://github.com/zostera/django-modeltrans/blob/a905f036a8c103b63ba39bb9079bf61ff2e24750/modeltrans/conf.py#L67)

Since `eng` is defined in `MODELTRANS_AVAILABLE_LANGUAGES`, the fallback _won't be_ triggered (https://github.com/zostera/django-modeltrans/blob/a905f036a8c103b63ba39bb9079bf61ff2e24750/modeltrans/fields.py#L132) and I get an empty value for `title_eng`.

`title_en` returns the `title` value as expected.

I do have #117 ready for review and would be happy to add additional tests if desired.
