### ISSUE TITLE
Admin mixin to hide certain languages in the change view

### ISSUE THREAD

**Issue by jieter** [zostera/django-modeltrans#16]
Currently, django-modeltrans shows all languages when using the change view in the django admin. More than a couple of languages will give too much clutter, so it would be nice to be able to show only the base language and the currently active language by adding a mixin to the model admin class.

**Comment by bulatshafigullin** [comment]
Hi, Jieter!  Totally aggree with you. 
![image](https://user-images.githubusercontent.com/503265/30069570-bbf5c148-9269-11e7-9136-5e92c27cb530.png)
And I need to add more :)

**Comment by jieter** [comment]
;)

Where does this view come from? Vanilla `django.contrib.admin`?

**Comment by bulatshafigullin** [comment]
Currently I'm using django-modeltranslation. And it also uses some js and css for making little tabs for each language
`class Media:
        js = (
            'modeltranslation/js/force_jquery.js',
            'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js',
            'tabbed_translation_fields.js',
            'yatr.js',
        )
        css = {
            'screen': ('modeltranslation/css/tabbed_translation_fields.css',),
        }`

**Comment by bulatshafigullin** [comment]
Sorry about code format, can't make it any better with indentation :(

**Comment by bulatshafigullin** [comment]
It's from here http://django-modeltranslation.readthedocs.io/en/latest/admin.html#using-tabbed-translation-fields

**Comment by jieter** [comment]
Work started on this in branch admin-mixins. Very simple for now, but it reduces the clutter big time and I don't think the usecase of being able to edit all languages is really worth the effort.
