### ISSUE TITLE
Fallback to default language when subcodes are used

### ISSUE THREAD

**Issue by dyve** [zostera/django-modeltrans#18]
When a language with a subcode is requested, e.g. `pt-BR`, and a translation is not available, we should fall back to the main language (in this example: `pt`) before falling back to the fallback language.

**Comment by dyve** [comment]
Note that capitalization might be an issue here, forcing upper or lower case might be best. I don't think the user should be punished for requesting `pt-br` instead of `pt-BR`. This might be a separate issue.

**Comment by jieter** [comment]
This should be configured explicitly in the new `MODELTRANS_FALLBACK` setting, refs #20
