### ISSUE TITLE
AddIndex in initial migration created for model with translation field fails

### ISSUE THREAD

**Issue by jieter** [zostera/django-modeltrans#36]

**Comment by brunovila** [comment]
I experimented the same

**Comment by jieter** [comment]
I suspect this is a django bug: https://code.djangoproject.com/ticket/28888, or at least something not very clearly defined in django. There is also a [mailing list thread](https://groups.google.com/forum/#!searchin/django-developers/28888%7Csort:date/django-developers/Ov7PpCbFA68/pbm6Fe1HAAAJ)

**Comment by jieter** [comment]
Django doesn't support custom indexes for model fields (yet). For the time being, adding them manually is way better than the current unpredictable ordering.

```python
class Category(models.Model):
    name = models.CharField(max_length=255)
    i18n = TranslationField(fields=("name",))

    class Meta:
        indexes = [GinIndex(fields=["i18n"]]
```
