### ISSUE TITLE
Why change dash to underscore on the language part?

### ISSUE THREAD

**Issue by ivanrvpereira** [zostera/django-modeltrans#54]
```python
def build_localized_fieldname(field_name, lang):
    if lang == "id":
        # The 2-letter Indonesian language code is problematic with the
        # current naming scheme as Django foreign keys also add "id" suffix.
        lang = "ind"
    return str("{}_{}".format(field_name, lang.replace("-", "_")))
```
I find this a bit odd. As an example, I have `pt-br` and fields are stored as `name_pt_br`. This is harder to reverse.
I'm pretty sure you have a reason to do it, my question goal is to understand the reason.

Thanks

**Comment by ivanrvpereira** [comment]
Forget, it's because `name_pt-br` is not a valid method name. The conversion to underscore could be made when access to the field, but this clarifies my question.

**Comment by jartaud** [comment]
@ivanrvpereira how did you manage to get pt-br working? I have es-mx and both `model.name_i18n` and `model.name_es_mx` keep falling back to `model.name`.
