### ISSUE TITLE
Related lookups

### ISSUE THREAD

**Issue by eriktelepovsky** [zostera/django-modeltrans#59]
Hi. Are related field lookups supported? If not, is there a plan to do so?

**Sample:**

This is not working:

```
listings = Listing.objects.filter(categories__slug_i18n__in=value)
```

Exception:

```
File "/Users/erik/env/ultralist-tenant/lib/python3.7/site-packages/django/db/backends/postgresql/operations.py", line 105, in quote_name
    if name.startswith('"') and name.endswith('"'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Current workaround:

```
categories = Category.objects.filter(slug_i18n__in=value)
listings = Listing.objects.filter(categories__in=categories)
```

Thanks a lot.

**Comment by jieter** [comment]
They are, but require you to manually add [`MultiLingualManager`](https://django-modeltrans.readthedocs.io/en/latest/pages/reference.html#modeltrans.manager.MultilingualManager) to the other side:

> If you want to use translated fields when building the query from a related model, you need to add `objects = MultilingualManager()` to the model you want to build the query from.
> 
> For example, `Category` needs `objects = MultilingualManager()` in order to allow `Category.objects.filter(blog__title_i18n__icontains='django')`:
> 
```python
class Category(models.Model):
    title = models.CharField(max_length=255)

    objects = MultilingualManager()  # required to use translated fields of Blog.

class Blog(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField(null=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)

    i18n = TranslationField(fields=("title", "body"))
```

**Comment by eriktelepovsky** [comment]
Perfect, thanks.
