### ISSUE TITLE
How to change default LANGUAGE_CODE

### ISSUE THREAD

**Issue by eriktelepovsky** [zostera/django-modeltrans#61]
Hi. I'd like to ask for help how to safely change LANGUAGE_CODE in the settings.

I started project with default language "sk" and created around 500 translations into language "en" across whole database in different models. Later I realised it would be better to have "en" as a default language, so I changed the settings.LANGUAGE_CODE to "en". The issue is, the translations are still saved in regular table column in language "sk" and i18n column contains "en" translations. If I understand it correctly, it needs to be switched. Can anybody guide me how to do it safely without losing translated data, please?

Thank you very much.

**Comment by jieter** [comment]
@eriktelepovsky You should do this by writing a custom [data migration](https://docs.djangoproject.com/en/3.1/topics/migrations/#data-migrations).

1. make sure to have a backup.
2. move contents of `i18n.<field>_sk` to `i18n.<field>_en`
3. move contents of `<field>` to `i18n.<field>_sk`
4. move contents of `i18n.<field>_en` to `<field>`

It could look something like this:
```python
from django.db import migrations

def change_default_language(apps, schema_editor):
    Blog = apps.get_model('yourappname', 'Blog')
    for blog in Blog.objects.all():
        title_en = blog.i18n["title_sk"]
        title_sk = blog.title
        blog.title = title_en
        # ... repeat for all translated fields in this model
        blog.i18n = {"title_sk": title_sk, "content_sk": ...}
        blog.save()

    # ... repeat for all models with translated fields

class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_default_language),
    ]
```
