### ISSUE TITLE
enhancement - use json for the translatable fields

### ISSUE THREAD

**Issue by zhengfen** [zostera/django-modeltrans#76]
for a model, if the title is translatable, then use json type for title field, and save title like: 
{'en': 'english title', 'fr':'titre français'}

similar to  the package for laravel:  https://github.com/spatie/laravel-translatable

**Comment by jieter** [comment]
Hi @zhengfen, thanks for your suggestion. Implementing it would require a rewrite of most of the code in this project, and a data migration for existing use. 

It is therefore out of scope for this project.
