### ISSUE TITLE
Use django.db.models.fields.json.KeyTransform

### ISSUE THREAD

**Issue by pikhovkin** [zostera/django-modeltrans#79]
Use django.db.models.fields.json.KeyTransform instead of django.contrib.postgres.fields.jsonb.KeyTransform - [doc](https://docs.djangoproject.com/en/3.1/releases/3.1/#postgresql-jsonfield).

I think that when solving this issue, the https://github.com/zostera/django-modeltrans/issues/76 issue will be solved automatically. At least for me since I am using sqlite for tests.

**Comment by jieter** [comment]
Should be fixed with #78 right? Just released [0.7.2](https://pypi.python.org/pypi/django-modeltrans/0.7.2) today.
